steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE', 'services/$_SERVICE/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '--allow-unauthenticated'
    - '--platform=managed'
    - '--region=$_REGION'
    - '--image=gcr.io/$PROJECT_ID/$_SERVICE'
    - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,HWSH_GATEWAY_SA=$_HWSH_GATEWAY_SA,HWSH_ENVIRONMENT=$_HWSH_ENVIRONMENT'
    - '$_PREFIX-$_SERVICE'