steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      curl --http1.1 --silent --fail -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://servicemanagement.googleapis.com/v1/services/$_API_NAME/configs/$_API_CONFIG" -o /workspace/services/$_SERVICE/service.json
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE', 'services/$_SERVICE/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '--region=$_REGION'
    - '--image=gcr.io/$PROJECT_ID/$_SERVICE'
    - '$_PREFIX-$_SERVICE'